## nput data and prefix ##
bam: "tmp.bam"
bai: "tmp.bai"
vcf: "tmp.vcf"
outdir : "results"
OUTPREFIX: "postprocess"

## Overall reference resources
ref: "hsapiens.hs37d5.fasta"
ref_fai: "hsapiens.hs37d5.fasta.fai"
ref_dict: "hsapiens.hs37d5.dict"
repmask_bed: "SmartRNASeqCaller/resources/repmasker_hg19.bed.gz"
intron_bed: "SmartRNASeqCaller/resources/intron_4bp_splice_overla.bed.gz"
rnaedit_bed: "SmartRNASeqCaller/resources/merged_RNA_edit.bed.gz"
model: "SmartRNASeqCaller/resources/RNA_Variant_RF_model.rds"

## paths to tools
GATK: "/usr/GenomeAnalysisTK.jar"
python:  "/opt/conda/bin/python2.7" 
#Full Path to SmartRNASeqCaller locally
pp_path: "/..../SmartRNASeqCaller"

