## Input data and prefix ##
bam: "Step5_out.bam"
bai: "Step5_out.bam.bai"
vcf: "Step8_out.filtered.g.vcf"
outdir : "results"
OUTPREFIX: "postprocess"

## Overall reference resources
ref: "/home/bhaas/CTAT_GENOMICS/GRCh37_gencode_v19_CTAT_lib_Aug152019.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa"
ref_fai: "/home/bhaas/CTAT_GENOMICS/GRCh37_gencode_v19_CTAT_lib_Aug152019.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa.fai"
ref_dict: "/home/bhaas/CTAT_GENOMICS/GRCh37_gencode_v19_CTAT_lib_Aug152019.plug-n-play/ctat_genome_lib_build_dir/ref_genome.dict"
repmask_bed: "resources/hg19/repmasker_hg19.bed.gz"
intron_bed: "resources/hg19/intron_4bp_splice_overlap.bed.gz"
rnaedit_bed: "resources/hg19/merged_RNA_edit.bed.gz"
model: "resources/RNA_Variant_RF_model.rds"

## paths to tools [docker image paths]
GATK: "/usr/GenomeAnalysisTK.jar"
python:  "/opt/conda/bin/python2.7" 
#Full Path to SmartRNASeqCaller (in docker image: /opt/SmartRNASeqCaller or
# Locally : your path to SmartRNASeqCaller
#pp_path: "/..../SmartRNASeqCaller"
pp_path: "/opt/SmartRNASeqCaller"
